// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;

#nullable disable

namespace Fish_Shield_API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CORE.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalPhoto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("AppUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CORE.Models.CausativeAgents", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Agents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiseaseID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DiseaseID");

                    b.ToTable("CausativeAgents");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Agents = "Identification: Streptococcus iniae is isolated and identified as the primary pathogen causing streptococcosis in tilapia.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 2,
                            Agents = "Characterization: Its morphological, biochemical, and molecular properties are examined to confirm its identity.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 3,
                            Agents = "Virulence Factors: S. iniae possesses adhesion proteins, enzymes, and toxins that contribute to its ability to infect and cause disease in tilapia.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 4,
                            Agents = "Host-Pathogen Interaction: The bacterium infects tilapia through breaches in the skin or mucosal surfaces, colonizing tissues and evading immune defenses.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 5,
                            Agents = "Disease Manifestation: Infection leads to streptococcosis, resulting in systemic dissemination and clinical signs in affected tilapia.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 6,
                            Agents = "EUS is caused by Aphanomyces invadans , a fungus belonging to Saprolegniales, Oomycetida, and is classified in Stramenopiles or Chromista along with diatoms and brown algae. Disinfection of infected fish pond by hydrated lime and addition of salt to inhibit the fungus has been used in EUS outbreaks",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 7,
                            Agents = "Bacterial Pathogen: Flavobacterium columnare is the causative agent of Columnaris disease in tilapia.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 8,
                            Agents = "Gram-Negative Bacterium: It is a Gram-negative bacterium commonly found in freshwater environments.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 9,
                            Agents = "Characteristic Appearance: F. columnare forms slimy colonies resembling columns, hence the name \"Columnaris.\"",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 10,
                            Agents = "Skin and Gill Affliction: It primarily affects the skin and gills of tilapia, causing white or grayish patches resembling cotton wool.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 11,
                            Agents = "Bacterial gill disease typically occurs as a result of poor living conditions, such as overcrowding, poor water quality, high organic debris, increased temperature of the water, and increased ammonia levels. While it is most often the young and/or weak fish that contract the disease, due to their vulnerable immune systems, gill disease can affect fish of any age.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 12,
                            Agents = "The bacteria that cause gill infections are primarily Flavobacteria, Aeromonas and Pseudomonas spp. The direct initiating cause by these bacteria is not conclusive, but they will often be found as secondary, opportunistic infections.",
                            DiseaseID = 4
                        });
                });

            modelBuilder.Entity("CORE.Models.ClinicalSigns", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DiseaseID")
                        .HasColumnType("int");

                    b.Property<string>("Sign")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DiseaseID");

                    b.ToTable("ClinicalSigns");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DiseaseID = 1,
                            Sign = "Lethargy and reduced activity levels."
                        },
                        new
                        {
                            ID = 2,
                            DiseaseID = 1,
                            Sign = "Loss of appetite and reduced feeding behavior."
                        },
                        new
                        {
                            ID = 3,
                            DiseaseID = 1,
                            Sign = "Skin lesions, including ulcers, reddening, and hemorrhages."
                        },
                        new
                        {
                            ID = 4,
                            DiseaseID = 1,
                            Sign = "Pop-eye (exophthalmia) due to eye swelling."
                        },
                        new
                        {
                            ID = 5,
                            DiseaseID = 1,
                            Sign = "Abnormal swimming behavior and respiratory distress."
                        },
                        new
                        {
                            ID = 6,
                            DiseaseID = 2,
                            Sign = "Fish usually develop red spots or small to large ulcerative lesions on the body. The early signs of the disease include loss of appetite and fish become darker. Infected fish may float near the surface of the water, and become hyperactive with a very jerky pattern of movement"
                        },
                        new
                        {
                            ID = 7,
                            DiseaseID = 3,
                            Sign = "White or grayish patches resembling cotton wool on the skin, fins, and gills."
                        },
                        new
                        {
                            ID = 8,
                            DiseaseID = 3,
                            Sign = "Ulcerations and lesions on the skin, often accompanied by inflammation."
                        },
                        new
                        {
                            ID = 9,
                            DiseaseID = 3,
                            Sign = "Loss of scales and fin rot."
                        },
                        new
                        {
                            ID = 10,
                            DiseaseID = 3,
                            Sign = "Respiratory distress, including rapid gill movement or gasping at the water surface."
                        },
                        new
                        {
                            ID = 11,
                            DiseaseID = 3,
                            Sign = "Behavioral changes such as lethargy and loss of appetite."
                        },
                        new
                        {
                            ID = 12,
                            DiseaseID = 4,
                            Sign = "Bacterial Gill Disease will attack your fish's gills, causing them to rot and erode. This will make it harder for your fish to breath, so you may see it gasping for air at the water surface or rapid gill movement. Unsurprisingly, your fish will also have little appetite and may be losing weight"
                        });
                });

            modelBuilder.Entity("CORE.Models.DetectDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<string>("FishPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfDisFromAIModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("UserId");

                    b.ToTable("Detects");
                });

            modelBuilder.Entity("CORE.Models.Diagnosis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Diagones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiseaseID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DiseaseID");

                    b.ToTable("Diagnosis");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Diagones = "Clinical Observation: Identify clinical signs such as lethargy, loss of appetite, skin lesions, pop-eye, and respiratory distress in affected tilapia.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 2,
                            Diagones = "Sample Collection: Collect tissue samples (e.g., liver, spleen) from affected fish for laboratory analysis.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 3,
                            Diagones = "Bacterial Isolation: Isolate Streptococcus bacteria from the tissue samples using appropriate culture techniques.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 4,
                            Diagones = "Confirmation: Confirm the presence of Streptococcus iniae or other relevant species through bacterial identification tests, such as PCR or biochemical assays.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 5,
                            Diagones = "Clinical Examination: Fish displaying symptoms such as ulcerative lesions on the skin and fins are examined closely for characteristic signs of EUS.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 6,
                            Diagones = "Microscopic Analysis: Samples of affected tissue, such as skin or fin lesions, are collected and examined under a microscope to identify the presence of Aphanomyces invadans, the fungus responsible for EUS.\r\n",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 7,
                            Diagones = "Culture and Molecular Techniques: The fungus can be cultured from tissue samples to confirm its presence and identify its characteristics. Molecular techniques such as PCR (polymerase chain reaction) may also be employed for more rapid and specific detection of Aphanomyces invadans DNA.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 8,
                            Diagones = "Histopathology: Histopathological examination of tissue samples can provide additional insights into the extent of tissue damage and the inflammatory response associated with EUS.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 9,
                            Diagones = "Clinical Examination: Identify clinical signs such as white or grayish patches resembling cotton wool on the skin, fins, and gills, as well as ulcerations and lesions.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 10,
                            Diagones = "Microscopic Examination: Examine skin and gill smears under a microscope for characteristic bacterial colonies and signs of infection.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 11,
                            Diagones = "Bacterial Culture: Perform bacterial culture to isolate and identify Flavobacterium columnare.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 12,
                            Diagones = "Confirmation: Confirm the diagnosis based on clinical signs, microscopic examination, and bacterial culture results.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 13,
                            Diagones = "Diagnosis of bacterial gill disease depends on the detection of large numbers of filamentous bacteria on the gills. Along with the clinical signs described above, this observation represents diagnostic evidence of the disease. there are several forms for diagnosing Bacterial gill disease:",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 14,
                            Diagones = "Microscopic Examination: To diagnose gill disease, a microscopic examination of the affected gill tissue is typically performed. The presence of fungal hyphae, spores, or other characteristic structures can confirm the infection. The examination may involve taking a small sample of the gill tissue and staining it for microscopic observation.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 15,
                            Diagones = "Laboratory Culture: In some cases, the pathogenic fungus may need to be cultured in a laboratory setting to confirm the diagnosis. This involves growing the fungus from a sample taken from the affected gills on specific culture media. The growth characteristics and appearance of the cultured fungus can help identify the causative organism.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 16,
                            Diagones = "Differential Diagnosis: Other diseases or conditions can cause similar symptoms to gill disease, so it is essential to consider differential diagnoses. These can include other fungal infections, bacterial infections, parasitic infestations, and environmental factors like poor water quality.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 17,
                            Diagones = "Veterinary Consultation: If gill disease is suspected, it is advisable to consult a veterinarian or fish health professional with experience in aquatic diseases. They can perform the necessary diagnostic tests, provide treatment recommendations, and offer guidance on disease prevention and management.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 18,
                            Diagones = "Early diagnosis and prompt treatment are crucial in managing gill disease. Treatment typically involves antifungal medications, which may be administered orally, through the water, or by injection, depending on the severity of the infection. Additionally, addressing any underlying environmental issues, such as poor water quality or stressors, is essential to prevent disease recurrence.",
                            DiseaseID = 4
                        });
                });

            modelBuilder.Entity("CORE.Models.Equipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("OwnerId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("CORE.Models.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("CORE.Models.FishDisease", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Name");

                    b.ToTable("FishDiseases");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Streptococcosis is a systemic bacterial infection affecting tilapia, primarily caused by Streptococcus iniae. It poses a significant threat to tilapia aquaculture globally, leading to morbidity and mortality in affected populations.",
                            Name = "Streptococcosis Disease",
                            Type = "Bacterial Disease"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Epizootic Ulcerative Syndrome (EUS) is a devastating infectious disease that primarily affects freshwater and estuarine fish species. It is caused by the fungus Aphanomyces invadans. EUS is characterized by the development of ulcerative lesions on the skin and fins of affected fish, which can lead to tissue necrosis and systemic infection. The disease is often associated with warm water temperatures and environmental stressors. EUS outbreaks can result in high mortality rates, significant economic losses for aquaculture operations, and ecological impacts on wild fish populations.",
                            Name = "Epizootic ulcerative syndrome (EUS)",
                            Type = "Fungal disease"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Columnaris disease, also known as cotton wool disease or saddleback disease, is a common bacterial infection affecting tilapia. It is caused by the bacterium Flavobacterium columnare. Columnaris disease typically presents as a systemic infection, primarily affecting the skin and gills of tilapia, although it can also impact other organs.",
                            Name = "Columnaris Disease",
                            Type = "Bacterial Disease"
                        },
                        new
                        {
                            ID = 4,
                            Description = "(BGD) is a common external infection of hatchery reared salmonids and occasionally of warm water species reared under intensive conditions. As defined by Wood (1974), the name of the disease describes the clinical signs of bacterial infections on the gills. The etiological agent of the disease is considered to be one or more species of filamentous bacteria including Flavobacterium sp. as most recently described by Wakabayashi et al. (1980). BGD is characterized by the presence of large numbers of filamentous bacteria on the gills accompanied by fusing and clubbing of the gill filaments. Acute or chronic forms of the disease may occur and acute outbreaks may involve daily mortality rates approaching 20% (Warren 1981). The onset of bacterial gill disease usually follows a deterioration of environmental conditions associated with overcrowding and increases in toxic metabolic waste products. According to Wood (1979), fish smaller than 90-100/lb are most susceptible to the disease. Successful treatment can only be accomplished through prompt therapy and alleviation of poor environmental conditions.",
                            Name = "Gill Disease",
                            Type = "bacterial, viral, or parasitic Disease"
                        });
                });

            modelBuilder.Entity("CORE.Models.ImpactOnAquaculture", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DiseaseID")
                        .HasColumnType("int");

                    b.Property<string>("ImpactOnAquaculturee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DiseaseID");

                    b.ToTable("ImpactOnAquaculture");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DiseaseID = 1,
                            ImpactOnAquaculturee = "Economic Losses: Streptococcosis outbreaks can lead to high mortality rates in affected fish populations, resulting in economic losses for tilapia farmers. Mortality can occur at any stage of production, from juvenile to market size, affecting both production efficiency and profitability."
                        },
                        new
                        {
                            ID = 2,
                            DiseaseID = 1,
                            ImpactOnAquaculturee = "Reduced Growth Rates: Infected tilapia often exhibit reduced growth rates and poor feed conversion efficiency, leading to prolonged production cycles and decreased marketable sizes. This results in decreased productivity and increased production costs."
                        },
                        new
                        {
                            ID = 3,
                            DiseaseID = 1,
                            ImpactOnAquaculturee = "Treatment Costs: Treating streptococcosis infections in tilapia requires the administration of antibiotics, which adds to production costs. Additionally, repeated use of antibiotics can contribute to the development of antimicrobial resistance, posing long-term challenges for disease management in aquaculture."
                        },
                        new
                        {
                            ID = 4,
                            DiseaseID = 1,
                            ImpactOnAquaculturee = "Market Access Restrictions: Streptococcosis outbreaks may lead to market access restrictions or trade bans on affected tilapia products due to concerns about food safety and public health. This can further exacerbate economic losses for tilapia farmers and impact the reputation of the aquaculture industry."
                        },
                        new
                        {
                            ID = 5,
                            DiseaseID = 1,
                            ImpactOnAquaculturee = "Environmental Impact: Streptococcosis outbreaks can result in increased nutrient loading and microbial contamination in aquaculture systems, potentially leading to environmental degradation and negative impacts on water quality and ecosystem health."
                        },
                        new
                        {
                            ID = 6,
                            DiseaseID = 2,
                            ImpactOnAquaculturee = "Economic Losses: EUS outbreaks can lead to mass mortality events, resulting in substantial financial losses for aquaculture businesses due to the death of fish stocks and reduced production."
                        },
                        new
                        {
                            ID = 7,
                            DiseaseID = 2,
                            ImpactOnAquaculturee = "Production Disruption: Disease outbreaks can disrupt aquaculture production schedules, leading to delays in harvesting or stocking and affecting market supply and demand dynamics."
                        },
                        new
                        {
                            ID = 8,
                            DiseaseID = 2,
                            ImpactOnAquaculturee = "Increased Costs: Controlling and managing EUS outbreaks often require additional expenses for disease treatment, water quality management, and implementing biosecurity measures, increasing overall production costs."
                        },
                        new
                        {
                            ID = 9,
                            DiseaseID = 2,
                            ImpactOnAquaculturee = "Market Perception: Public perception of EUS outbreaks can negatively affect consumer confidence in the safety and quality of farmed fish products, potentially leading to decreased market demand and sales."
                        },
                        new
                        {
                            ID = 10,
                            DiseaseID = 2,
                            ImpactOnAquaculturee = "Regulatory Scrutiny: EUS outbreaks may attract regulatory attention, leading to increased oversight, stricter regulations, and compliance requirements for aquaculture operations, further adding to operational challenges and costs."
                        },
                        new
                        {
                            ID = 11,
                            DiseaseID = 3,
                            ImpactOnAquaculturee = "Economic Losses: Columnaris disease leads to economic losses in tilapia aquaculture due to morbidity, mortality, and treatment costs."
                        },
                        new
                        {
                            ID = 12,
                            DiseaseID = 3,
                            ImpactOnAquaculturee = "Decreased Growth Rates: Infected tilapia exhibit reduced growth rates and poor feed conversion efficiency."
                        },
                        new
                        {
                            ID = 13,
                            DiseaseID = 3,
                            ImpactOnAquaculturee = "Marketability: It can reduce the marketability of infected fish due to skin lesions, fin rot, and other clinical signs."
                        },
                        new
                        {
                            ID = 14,
                            DiseaseID = 3,
                            ImpactOnAquaculturee = "Overall Health Impact: Outbreaks compromise the overall health of tilapia populations, impacting the sustainability of aquaculture operations."
                        },
                        new
                        {
                            ID = 15,
                            DiseaseID = 3,
                            ImpactOnAquaculturee = "Treatment Challenges: Treatment involves antibiotics, adding to production costs and posing challenges due to antimicrobial resistance concerns."
                        },
                        new
                        {
                            ID = 16,
                            DiseaseID = 4,
                            ImpactOnAquaculturee = "Economic Losses: Bacterial gill diseases can lead to high mortality rates among fish populations, resulting in economic losses for aquaculture producers due to decreased yields and potential market losses."
                        },
                        new
                        {
                            ID = 17,
                            DiseaseID = 4,
                            ImpactOnAquaculturee = "Treatment Costs: Treating bacterial gill diseases often requires the use of antibiotics or other medications, which can be costly for aquaculture operations. Additionally, the labor and resources required for disease management further add to production expenses."
                        },
                        new
                        {
                            ID = 18,
                            DiseaseID = 4,
                            ImpactOnAquaculturee = "Environmental Impact: The use of antibiotics and other medications in aquaculture to control bacterial gill diseases can contribute to the development of antibiotic resistance in bacteria, posing risks to human health and the environment."
                        },
                        new
                        {
                            ID = 19,
                            DiseaseID = 4,
                            ImpactOnAquaculturee = "Biosecurity Risks: Bacterial gill diseases can spread rapidly within aquaculture facilities, especially in densely stocked systems. Poor biosecurity practices can further exacerbate disease transmission and impact overall farm health."
                        },
                        new
                        {
                            ID = 20,
                            DiseaseID = 4,
                            ImpactOnAquaculturee = "Market Reputation: Recurrent outbreaks of bacterial gill diseases can damage the reputation of aquaculture producers and their products in the market, leading to decreased consumer confidence and potential market rejection."
                        });
                });

            modelBuilder.Entity("CORE.Models.PaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("StripePaymentRecords");
                });

            modelBuilder.Entity("CORE.Models.PreventionAndControll", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DiseaseID")
                        .HasColumnType("int");

                    b.Property<string>("Prevention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DiseaseID");

                    b.ToTable("PreventionAndControll");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DiseaseID = 1,
                            Prevention = "Quarantine protocols for new fish introductions."
                        },
                        new
                        {
                            ID = 2,
                            DiseaseID = 1,
                            Prevention = "Disinfection of equipment and facilities."
                        },
                        new
                        {
                            ID = 3,
                            DiseaseID = 1,
                            Prevention = "Minimization of stressors through proper husbandry practices"
                        },
                        new
                        {
                            ID = 4,
                            DiseaseID = 1,
                            Prevention = "Implementation of vaccination programs where feasible."
                        },
                        new
                        {
                            ID = 5,
                            DiseaseID = 1,
                            Prevention = "Surveillance and early intervention in case of disease outbreaks."
                        },
                        new
                        {
                            ID = 6,
                            DiseaseID = 2,
                            Prevention = "Isolation and Screening: Quarantine new fish and screen them for disease."
                        },
                        new
                        {
                            ID = 7,
                            DiseaseID = 2,
                            Prevention = "Biosecurity: Tighten facility access and disinfect regularly."
                        },
                        new
                        {
                            ID = 8,
                            DiseaseID = 2,
                            Prevention = "Water Quality: Maintain optimal conditions to reduce stress."
                        },
                        new
                        {
                            ID = 9,
                            DiseaseID = 2,
                            Prevention = "Stocking and Care: Avoid overcrowding and ensure proper care."
                        },
                        new
                        {
                            ID = 10,
                            DiseaseID = 2,
                            Prevention = "Environment: Manage water quality and sediment effectively."
                        },
                        new
                        {
                            ID = 11,
                            DiseaseID = 2,
                            Prevention = "Monitoring: Regularly check for pathogens to catch outbreaks early."
                        },
                        new
                        {
                            ID = 12,
                            DiseaseID = 2,
                            Prevention = "Vaccination: Support vaccine development for long-term protection."
                        },
                        new
                        {
                            ID = 13,
                            DiseaseID = 2,
                            Prevention = "Regulations: Enforce rules to maintain responsible aquaculture practices."
                        },
                        new
                        {
                            ID = 14,
                            DiseaseID = 3,
                            Prevention = "Antibiotic Therapy: Administer antibiotics such as florfenicol or oxytetracycline under veterinary supervision."
                        },
                        new
                        {
                            ID = 15,
                            DiseaseID = 3,
                            Prevention = "Topical Treatments: Apply topical treatments or baths with antimicrobial agents to affected fish, targeting the infection directly."
                        },
                        new
                        {
                            ID = 16,
                            DiseaseID = 3,
                            Prevention = "Supportive Care: Provide supportive care, including maintaining optimal water quality and nutrition, to enhance the fish's immune response and aid in recovery."
                        },
                        new
                        {
                            ID = 17,
                            DiseaseID = 3,
                            Prevention = "Quarantine: Isolate infected fish to prevent the spread of the disease to other individuals in the population."
                        },
                        new
                        {
                            ID = 18,
                            DiseaseID = 3,
                            Prevention = "Implement early intervention and treatment protocols in case of disease outbreaks."
                        },
                        new
                        {
                            ID = 19,
                            DiseaseID = 4,
                            Prevention = "The best way to prevent bacterial gill disease from occurring is by maintaining hygienic living conditions for your fish."
                        },
                        new
                        {
                            ID = 20,
                            DiseaseID = 4,
                            Prevention = "Keeping the water clean of organic debris, giving the fish plenty of space in which to move, with no overcrowding"
                        },
                        new
                        {
                            ID = 21,
                            DiseaseID = 4,
                            Prevention = "maintaining a consistent temperature"
                        },
                        new
                        {
                            ID = 22,
                            DiseaseID = 4,
                            Prevention = "testing the water quality regularly to ensure that it is balanced are all the best practices for keeping your fish healthy and stress free"
                        },
                        new
                        {
                            ID = 23,
                            DiseaseID = 4,
                            Prevention = "Additionally, filters should be changed every month or checked according to the filter manufacturer's directions."
                        });
                });

            modelBuilder.Entity("CORE.Models.Rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ownerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ownerId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("CORE.Models.RecommandationActions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiseaseID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DiseaseID");

                    b.ToTable("RecommandationActions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Action = "Biosecurity Measures: Implement strict biosecurity protocols to prevent the introduction and spread of the bacteria.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 2,
                            Action = "Water Quality Management: Maintain optimal water quality parameters to reduce stress on tilapia and support their immune function.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 3,
                            Action = "Regular Health Monitoring: Conduct routine health assessments to detect early signs of infection and initiate timely interventions.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 4,
                            Action = "Vaccination: Utilize available and effective vaccines to confer immunity against Streptococcus iniae.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 5,
                            Action = "Prompt Treatment: Diagnose and treat infected fish promptly with appropriate antibiotics under veterinary supervision.",
                            DiseaseID = 1
                        },
                        new
                        {
                            ID = 6,
                            Action = "Early Detection: Regular monitoring for signs of EUS, such as ulcerative lesions on the skin and fins, is crucial for early detection and intervention.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 7,
                            Action = "Quarantine Measures: Implement quarantine protocols for new fish arrivals to prevent the introduction and spread of EUS to existing populations.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 8,
                            Action = "Biosecurity Protocols: Maintain strict biosecurity measures to minimize the risk of EUS transmission between aquaculture facilities and wild fish populations.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 9,
                            Action = "Environmental Management: Optimize water quality parameters and minimize environmental stressors to reduce the susceptibility of fish to EUS infection.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 10,
                            Action = "Treatment: Investigate and implement appropriate treatment options, such as antifungal medications, under the guidance of a veterinarian or aquatic health professional.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 11,
                            Action = "Sanitation: Ensure proper hygiene practices, including disinfection of equipment and facilities, to prevent the buildup and spread of EUS-causing pathogens.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 12,
                            Action = "Research and Monitoring: Support ongoing research efforts to better understand the epidemiology and pathogenesis of EUS, and collaborate with relevant agencies for surveillance and monitoring of EUS outbreaks.",
                            DiseaseID = 2
                        },
                        new
                        {
                            ID = 13,
                            Action = "Water Quality Management: Maintain optimal water quality parameters to reduce stress on tilapia and minimize the risk of infection.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 14,
                            Action = "Biosecurity Measures: Implement strict biosecurity protocols to prevent the introduction and spread of F. columnare in aquaculture systems.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 15,
                            Action = "Regular Monitoring: Conduct routine health assessments and monitor fish behavior closely to detect early signs of infection.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 16,
                            Action = "Treatment: Administer antimicrobial treatments under veterinary supervision if infections occur.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 17,
                            Action = "Stress Reduction: Minimize stressors such as overcrowding, poor nutrition, and environmental fluctuations to enhance tilapia immune function.",
                            DiseaseID = 3
                        },
                        new
                        {
                            ID = 18,
                            Action = "Isolation: Separate affected fish from the main population to prevent disease spread.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 19,
                            Action = "Water Quality: Maintain optimal water conditions with regular monitoring and adjustments.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 20,
                            Action = "Treatment: Administer antibiotics or other medications as directed by a veterinarian.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 21,
                            Action = "Stress Reduction: Minimize stressors such as overcrowding and poor water quality.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 22,
                            Action = "Quarantine: Quarantine new arrivals to prevent introducing pathogens.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 23,
                            Action = "Biosecurity: Implement disinfection and hygiene practices to prevent disease transmission.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 24,
                            Action = "Monitoring: Monitor fish closely for changes in behavior and gill condition.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 25,
                            Action = "Consultation: Seek advice from experts for diagnosis and treatment guidance.",
                            DiseaseID = 4
                        },
                        new
                        {
                            ID = 26,
                            Action = "Prevention: Take preventive measures to avoid future outbreaks.",
                            DiseaseID = 4
                        });
                });

            modelBuilder.Entity("CORE.Models.Treatment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DiseaseID")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DiseaseID");

                    b.ToTable("Treatment");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DiseaseID = 1,
                            TreatmentDesc = "Antibiotic Therapy: Administer antibiotics effective against Streptococcus bacteria, such as florfenicol or oxytetracycline, following veterinary guidance."
                        },
                        new
                        {
                            ID = 2,
                            DiseaseID = 1,
                            TreatmentDesc = "Supportive Care: Provide supportive care, including maintaining optimal water quality, nutrition, and minimizing stressors to enhance fish immune function."
                        },
                        new
                        {
                            ID = 3,
                            DiseaseID = 1,
                            TreatmentDesc = "Topical Treatments: Employ topical treatments or baths with antimicrobial agents to target localized infections, especially for skin lesions."
                        },
                        new
                        {
                            ID = 4,
                            DiseaseID = 1,
                            TreatmentDesc = "Quarantine: Isolate infected fish to prevent the spread of the disease to other individuals in the population."
                        },
                        new
                        {
                            ID = 5,
                            DiseaseID = 1,
                            TreatmentDesc = "Monitoring: Monitor the progress of treatment closely and adjust treatment protocols as necessary based on the response of the infected fish"
                        },
                        new
                        {
                            ID = 6,
                            DiseaseID = 2,
                            TreatmentDesc = "Quarantine and Biosecurity: Infected fish should be isolated to prevent the spread of the disease to healthy populations. Implementing strict biosecurity measures in aquaculture facilities can help prevent the introduction and transmission of EUS."
                        },
                        new
                        {
                            ID = 7,
                            DiseaseID = 2,
                            TreatmentDesc = "Water Quality Management: Maintaining optimal water quality parameters such as temperature, pH, dissolved oxygen levels, and ammonia concentration can help reduce stress on fish and enhance their immune response to the disease."
                        },
                        new
                        {
                            ID = 8,
                            DiseaseID = 2,
                            TreatmentDesc = "Antimicrobial Treatment: In cases of severe infection, antimicrobial agents may be used to control secondary bacterial infections and prevent further tissue damage. However, the use of antibiotics should be carefully regulated to prevent the development of antimicrobial resistance."
                        },
                        new
                        {
                            ID = 9,
                            DiseaseID = 2,
                            TreatmentDesc = "Topical Treatments: Topical treatments such as antiseptic solutions or medicated baths may be applied directly to the ulcerated lesions to promote healing and prevent secondary infections."
                        },
                        new
                        {
                            ID = 10,
                            DiseaseID = 2,
                            TreatmentDesc = "Supportive Care: Providing appropriate nutrition and minimizing stress through proper husbandry practices can help boost the immune system of infected fish and improve their overall health."
                        },
                        new
                        {
                            ID = 11,
                            DiseaseID = 2,
                            TreatmentDesc = "Environmental Management: Implementing environmental modifications such as reducing stocking density, improving water circulation, and removing organic debris can create less favorable conditions for the pathogen responsible for EUS."
                        },
                        new
                        {
                            ID = 12,
                            DiseaseID = 2,
                            TreatmentDesc = "Vaccination: Research into the development of vaccines against EUS-causing pathogens is ongoing. Vaccination of susceptible fish populations may offer long-term protection against the disease."
                        },
                        new
                        {
                            ID = 13,
                            DiseaseID = 3,
                            TreatmentDesc = "Antibiotic Therapy: Administer antibiotics effective against Streptococcus bacteria, such as florfenicol or oxytetracycline, following veterinary guidance."
                        },
                        new
                        {
                            ID = 14,
                            DiseaseID = 3,
                            TreatmentDesc = "Supportive Care: Provide supportive care, including maintaining optimal water quality, nutrition, and minimizing stressors to enhance fish immune function."
                        },
                        new
                        {
                            ID = 15,
                            DiseaseID = 3,
                            TreatmentDesc = "Topical Treatments: Employ topical treatments or baths with antimicrobial agents to target localized infections, especially for skin lesions."
                        },
                        new
                        {
                            ID = 16,
                            DiseaseID = 3,
                            TreatmentDesc = "Quarantine: Isolate infected fish to prevent the spread of the disease to other individuals in the population."
                        },
                        new
                        {
                            ID = 17,
                            DiseaseID = 3,
                            TreatmentDesc = "Monitoring: Monitor the progress of treatment closely and adjust treatment protocols as necessary based on the response of the infected fish"
                        },
                        new
                        {
                            ID = 18,
                            DiseaseID = 4,
                            TreatmentDesc = "Bacterial gill disease must first be treated with a change in the living conditions of the fish. If they are crowded, they will need to be given more space, either in a larger aquarium, or separated into different aquariums. The cleanliness of the water and aquarium is paramount. A treatment of potassium permanganate and salt water additives can be used to help the fish heal and recover from the infection. The amount of salt you will use will depend upon the species you are treating, but it must be a salt that is specifically made for fish water, and it should only be in the prescribed amount. Antibiotic therapy may be used to treat secondary bacterial infections."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "08ea9d75-045b-4287-8fc3-2c7c42fd281a",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "4cbd6819-24d5-454b-a5ae-de77db5f6b02",
                            Name = "FarmOwner",
                            NormalizedName = "FARMOWNER"
                        },
                        new
                        {
                            Id = "5dcbe0e4-c81c-409b-95e5-a2f49b7b15c5",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CORE.Models.Admin", b =>
                {
                    b.HasBaseType("CORE.Models.AppUser");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = "c92e94ba-e685-4c00-a040-282606ee9e34",
                            AccessFailedCount = 0,
                            Age = 0,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "7f410cec-2fde-4326-89c3-90aaeecdd101",
                            Disabled = false,
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "admin",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "db2fd7f5-e6d1-4fa6-a29d-b909a42fd83b",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("CORE.Models.PaymentUserAccount", b =>
                {
                    b.HasBaseType("CORE.Models.AppUser");

                    b.Property<byte>("HasFreeTrialCount")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("PaymentUserAccount");
                });

            modelBuilder.Entity("CORE.Models.Doctor", b =>
                {
                    b.HasBaseType("CORE.Models.PaymentUserAccount");

                    b.Property<string>("Certificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoreInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("CORE.Models.FarmOwner", b =>
                {
                    b.HasBaseType("CORE.Models.PaymentUserAccount");

                    b.Property<string>("FarmAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("FarmOwner");
                });

            modelBuilder.Entity("CORE.Models.CausativeAgents", b =>
                {
                    b.HasOne("CORE.Models.FishDisease", "FishDisease")
                        .WithMany("CausativeAgents")
                        .HasForeignKey("DiseaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishDisease");
                });

            modelBuilder.Entity("CORE.Models.ClinicalSigns", b =>
                {
                    b.HasOne("CORE.Models.FishDisease", "FishDisease")
                        .WithMany("ClinicalSigns")
                        .HasForeignKey("DiseaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishDisease");
                });

            modelBuilder.Entity("CORE.Models.DetectDisease", b =>
                {
                    b.HasOne("CORE.Models.FishDisease", "Disease")
                        .WithMany()
                        .HasForeignKey("DiseaseId");

                    b.HasOne("CORE.Models.PaymentUserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CORE.Models.Diagnosis", b =>
                {
                    b.HasOne("CORE.Models.FishDisease", "FishDisease")
                        .WithMany("Diagnosis")
                        .HasForeignKey("DiseaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishDisease");
                });

            modelBuilder.Entity("CORE.Models.Equipment", b =>
                {
                    b.HasOne("CORE.Models.FarmOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CORE.Models.ImpactOnAquaculture", b =>
                {
                    b.HasOne("CORE.Models.FishDisease", "FishDisease")
                        .WithMany("ImpactOnAquacultures")
                        .HasForeignKey("DiseaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishDisease");
                });

            modelBuilder.Entity("CORE.Models.PaymentRecord", b =>
                {
                    b.HasOne("CORE.Models.FarmOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CORE.Models.PreventionAndControll", b =>
                {
                    b.HasOne("CORE.Models.FishDisease", "FishDisease")
                        .WithMany("PreventionAndControlls")
                        .HasForeignKey("DiseaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishDisease");
                });

            modelBuilder.Entity("CORE.Models.Rating", b =>
                {
                    b.HasOne("CORE.Models.Doctor", "Doctor")
                        .WithMany("Rates")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CORE.Models.FarmOwner", "owner")
                        .WithMany("Rates")
                        .HasForeignKey("ownerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("CORE.Models.RecommandationActions", b =>
                {
                    b.HasOne("CORE.Models.FishDisease", "FishDisease")
                        .WithMany("RecommandationActions")
                        .HasForeignKey("DiseaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishDisease");
                });

            modelBuilder.Entity("CORE.Models.Treatment", b =>
                {
                    b.HasOne("CORE.Models.FishDisease", "FishDisease")
                        .WithMany("Treatment")
                        .HasForeignKey("DiseaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishDisease");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CORE.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CORE.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CORE.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CORE.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CORE.Models.FishDisease", b =>
                {
                    b.Navigation("CausativeAgents");

                    b.Navigation("ClinicalSigns");

                    b.Navigation("Diagnosis");

                    b.Navigation("ImpactOnAquacultures");

                    b.Navigation("PreventionAndControlls");

                    b.Navigation("RecommandationActions");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("CORE.Models.Doctor", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("CORE.Models.FarmOwner", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
